### ISSUE TITLE
Error -> Unknow database 'idm'

### ISSUE THREAD

**Issue by pacs27** [FIWARE/tutorials.Identity-Management#10]
I have this error in this tutorial. The database 'idm' is not created.

Error in mysql:
`Unknown database 'idm'`

Error in KeyRock:
```
{ Error: Unknown database 'idm'

at Packet.asError (/opt/fiware-idm/node_modules/mysql2/lib/packets/packet.js:708:17)

at ClientHandshake.execute (/opt/fiware-idm/node_modules/mysql2/lib/commands/command.js:28:26)

at Connection.handlePacket (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:408:32)

at PacketParser.Connection.packetParser.p [as onPacket] (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:70:12)

at PacketParser.executeStart (/opt/fiware-idm/node_modules/mysql2/lib/packet_parser.js:75:16)

at Socket.Connection.stream.on.data (/opt/fiware-idm/node_modules/mysql2/lib/connection.js:77:25)

at Socket.emit (events.js:198:13)

at addChunk (_stream_readable.js:288:12)

at readableAddChunk (_stream_readable.js:269:11)

at Socket.Readable.push (_stream_readable.js:224:10)

at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

code: 'ER_BAD_DB_ERROR',

errno: 1049,

sqlState: '42000',

sqlMessage: 'Unknown database \'idm\'' } }
```

**Comment by jason-fox** [comment]
Please pull the latest  code base and re-try (so we have a common baseline). If the error is still occurring run:

```console
docker ps
docker logs fiware-keyrock
```

so I can see what services you have running.

**Comment by jason-fox** [comment]
```text
CONTAINER ID   IMAGE              COMMAND                  CREATED              STATUS                          PORTS                                                      NAMES
2fde90a0a33e   fiware/idm:7.9.1   "docker-entrypoint.s…"   About a minute ago   Up About a minute               0.0.0.0:3005->3005/tcp, 3000/tcp, 0.0.0.0:3443->3443/tcp   fiware-keyrock
9fa0e28c8da1   mysql:5.7          "docker-entrypoint.s…"   About a minute ago   Up About a minute               0.0.0.0:3306->3306/tcp, 33060/tcp                          db-mysql
```

And the following log:

```text
2021-02-03T14:01:22.857405100Z 
> fiware-idm@7.9.1 start /opt/fiware-idm
> node ./bin/www
2021-02-03T14:01:22.857540600Z 
Wed, 03 Feb 2021 14:01:23 GMT idm:config Setting IDM_PORT to environment value: 3005
Wed, 03 Feb 2021 14:01:23 GMT idm:config Setting IDM_HOST to environment value: http://localhost:3005
Wed, 03 Feb 2021 14:01:23 GMT idm:config Setting IDM_HTTPS_ENABLED to environment value: false
Wed, 03 Feb 2021 14:01:23 GMT idm:config Setting IDM_HTTPS_PORT to environment value: 3443
Wed, 03 Feb 2021 14:01:23 GMT idm:config Setting IDM_PDP_LEVEL to environment value: basic
Wed, 03 Feb 2021 14:01:23 GMT idm:config Setting IDM_DB_HOST to environment value: mysql-db
Wed, 03 Feb 2021 14:01:23 GMT idm:config Setting IDM_DB_PASS to environment value: ********
Wed, 03 Feb 2021 14:01:23 GMT idm:config Setting IDM_DB_USER to environment value: ********
Wed, 03 Feb 2021 14:01:23 GMT idm:config Setting IDM_DB_NAME to environment value: idm
Wed, 03 Feb 2021 14:01:23 GMT idm:config Setting IDM_DB_DIALECT to environment value: mysql
Wed, 03 Feb 2021 14:01:23 GMT idm:config Setting IDM_EMAIL_HOST to environment value: localhost
Wed, 03 Feb 2021 14:01:23 GMT idm:config Setting IDM_EMAIL_PORT to environment value: 25
Wed, 03 Feb 2021 14:01:23 GMT idm:config Setting IDM_EMAIL_ADDRESS to environment value: noreply@localhost
Wed, 03 Feb 2021 14:01:23 GMT idm:config ***********************************************
Wed, 03 Feb 2021 14:01:23 GMT idm:config WARNING: The current encryption keys match the defaults found in the plaintext
Wed, 03 Feb 2021 14:01:23 GMT idm:config          template file - please update for a production instance
Wed, 03 Feb 2021 14:01:23 GMT idm:config ***********************************************
mysql-db:3306 - Connection refused
retry after 5 seconds.
mysql-db:3306 - Connection refused
retry after 5 seconds.
mysql-db:3306 - Connection refused
retry after 5 seconds.
retry after 5 seconds.
mysql-db:3306 - Connection refused

Database created
Database migrated
Database seeded
****************
WARNING: Seeding database with an admin user using default credentials.
This user must be deleted when running on a production instance
****************
Wed, 03 Feb 2021 14:01:59 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:245:13
Wed, 03 Feb 2021 14:02:02 GMT idm:server Listening on port 3005
Wed, 03 Feb 2021 14:02:02 GMT idm:models Connection has been established successfully
```


As you can see `Setting IDM_DB_NAME to environment value: idm` and the database is seeded from scratch.

**Comment by pacs27** [comment]
Thank you very much Jason, now it works perfectly.

Was an error with the Keyrock container:
```
CONTAINER ID   IMAGE                         COMMAND                  CREATED          STATUS                    PORTS                                                      NAMES
3c77921a958c   fiware/idm:7.9.1-distroless   "/nodejs/bin/node ./…"   56 minutes ago   Up 56 minutes (healthy)   0.0.0.0:3005->3005/tcp, 3000/tcp, 0.0.0.0:3443->3443/tcp   fiware-keyrock
33dd172da9d5   mysql:5.7                     "docker-entrypoint.s…"   56 minutes ago   Up 56 minutes             0.0.0.0:3306->3306/tcp, 33060/tcp                          db-mysql
```
